### ISSUE TITLE
PHP 5 oop, naming conventions

### ISSUE THREAD

**Issue by Ruplahlava** [Kris-B/nanoPhotosProvider#1]
Hello,
would you mind, if i do some refactoring? :)

For example rewrite it to fulfill, php5 conventions, clearer variable names and split it to more files?

**Comment by Kris-B** [comment]
Please!
;-)

**Comment by Kris-B** [comment]
Please!
;-)

**Comment by Ruplahlava** [comment]
https://github.com/Ruplahlava/nanoPhotosProvider/tree/refactoring ! :)

**Comment by Kris-B** [comment]
Looks great! Many thanks.
I'm just waiting for your PR ;-)

**Comment by Ruplahlava** [comment]
It will take a while, i wrote it without testing, which i can do on ~saturday...
