### ISSUE TITLE
How do I get other layouts?

### ISSUE THREAD

**Issue by tyeeman** [Kris-B/nanoPhotosProvider#11]
I tried adding other layout settings to the script but either I get nothing on my gallery page or it's all strange looking. Can we not do this with nanoPhotosProvider and we are left with only the default layout? I wanted to try the "justified" or "cascading grid" layouts.

**Comment by Kris-B** [comment]
Actually nanoPhotosProvider only provides images and albums to nanoGallery. Layout is 100% handled by nanoGallery and is independant of nanoPhotosProvider.
What kind of issue do you have?

**Comment by tyeeman** [comment]
How do I get the justified or cascading grid layout? I assume I have to add some code to the "script" on my html page but no matter what I do I can't seem to make it work. Take a look here, then view page source code to see what I have to add to make it work - 

`http://padlr.net/nano/`

**Comment by Kris-B** [comment]
Please delete all the `_thumbnails` folders to force a new generation of the thumbnails.

**Comment by tyeeman** [comment]
OK, did that, still looks the same. I replaced the default script with your Justified Layout script (see source code of my site), and now I get strange layout. Take a look.

**Comment by Kris-B** [comment]
You have to change the thumbnail image size in your `nanoPhotosProvider.cfg` also.
Reminder to delete the `_thumbnails` folders each time you change the size to force a new generation of the thumbnails.

I will add a note about this in the documentation.

**Comment by tyeeman** [comment]
OK, tried that, still does not look right. I deleted the width and height from my index.html and set them to 250 in the config file. I tried setting width to 'auto' in the config file, but the page would not even load. I deleted all thumbnails before doing the above also.

**Comment by blubbsy** [comment]
iam facing the same problem as tyeeman and tried the same things. For me it looks like as the Provider creates only fixed thumbnails that it is not possible to create the justified layout in the gallery.

**Comment by blubbsy** [comment]
i had the same issue. What i did was creating bigger thumbnails and then you can use the layouts as you want.
