### ISSUE TITLE
How to select a certain album?

### ISSUE THREAD

**Issue by mgk89** [Kris-B/nanoPhotosProvider#13]
How do I have to set the setup for loading a certain album and not all albums that are in the storage folder?

Like 'albumList' or 'photoset' in the flickr setup?

**Comment by mgk89** [comment]
I tried pretty much everything: albumID, ID, album ... but the inital json string always submittes "?albumID=0"

Thanks for you help!

**Comment by Kris-B** [comment]
You just want to display the content of 1 and only 1 album?
with flickr:
- `albumList` will display 1 or several albums (and not directly the content)
- `photoset` will display only the content of 1 album
  Which one of theses 2 features do you need?

**Comment by mgk89** [comment]
Hi, thank you for your answer. 

No, I want to do it with the nanoPhotoProvider. But just like you can do it with Flickr. 

Right now I see all albums and images that are in my photoprovider folder, but I would like to select a certain album or a list of certain albums (like photoset or albumList) but without Flickr. 

I hope you know what I mean :) thanks in advance!

**Comment by Kris-B** [comment]
Ok, I understand that you want it with nanophotosprovider. But which one of these 2 features do you need `albumList` or `photoset`?

**Comment by mgk89** [comment]
Actually it would be wounderful, if both features would be available:

I'm using albumList for filtering galleries (f.ex. year, topic, place, ...) and photoset for direktlinking to an album in a blog-post.

So, if anyhow possible, it would be awesome if both could be realized! Thanks for your effort!

**Comment by Kris-B** [comment]
Both can be implemented, but they will not work if you have more than 1 level of folders.
Would this be ok for you?

**Comment by mgk89** [comment]
Yes that would be great! Thank you so much!

**Comment by Kris-B** [comment]
please check nanoPhotosProvider v0.9.3 and nanoGALLERY v5.10.0

**Comment by mgk89** [comment]
It works like a charm!!! Thank you very much, great stuff!!!

**Comment by Kris-B** [comment]
;-)
