### ISSUE TITLE
albumDescSeparator

### ISSUE THREAD

**Issue by mgk89** [Kris-B/nanoPhotosProvider#14]
a great feature would be if you could name the gallery folders like "1001$$Albumname" just like the seperator for files. So you could easily have all folders in a certain order.

A different (maybe easier) solution would be if the FolderTitle in the label could start after the fifth character: then a folder named "1001_Albumname" would be displayed as "Albumname" although it's real foldername would be "1001_Albumname".

I hope you understand what I mean :)

**Comment by Kris-B** [comment]
yes, nice feature --> will be added

**Comment by Kris-B** [comment]
Please check this version of nanoGallery: https://raw.githubusercontent.com/Kris-B/nanoGALLERY/master/jquery.nanogallery.js

filenames can start with @@NNNN where NNNN is a 4 digit number

**Comment by mgk89** [comment]
Hi, thank you for your work! :)

is this feature also compatible with your photoprovider plugin?

**Comment by Kris-B** [comment]
this feature is only for nanophotosprovider ;-)

**Comment by Kris-B** [comment]
this feature is include nanoGALLERY 5.10.3 

https://github.com/Kris-B/nanoGALLERY/releases/tag/v5.10.3
