### ISSUE TITLE
concern with _thumbnail being created in the same place as the original photos

### ISSUE THREAD

**Issue by msharp1** [Kris-B/nanoPhotosProvider#16]
Hi,

As a _thumbnail folder is created inside each folder level of the `nanoPhotosContent` folder, it means write permission should enabled recursively here. The concern I'm having is I don't want my whole original photo folder to be exposed with write permission.
I would instead suggest to have another folder dedicated to thumbs next to it, as `nanoPhotosThumbs` with write permission.
And rename the configuration directives like:

```
thumbsFolder="path/to/nanoPhotosThumbs"
originalImageFolder="path/to/custom/readonly/imagefolder"
```

Cheers !

**Comment by Kris-B** [comment]
Hi,
The whole photo folder needs write permission, but only for server side applications. No one from "outside" can write/delete in this folder.

I'm trying to keep nanoPhotosProvider as simple as possible. The goal is not to replace a full photo management software. Having the thumbnails in another folder tree, means that the user needs to manage 2 folder trees, and I'm not convinced that this is user friendly enough.

Chris
