### ISSUE TITLE
Problems with implementing

### ISSUE THREAD

**Issue by tsalat** [Kris-B/nanoPhotosProvider#3]
Hi,

i came across this script while searching for something suitable for publishing a gallery with random photos of my daughter and i must say that this solution is absolutely ideal in all ways, but i have a problem with make this working properly. I set up so far just a testing html with 3 images in the root folder and 2 folders containing again 3 images each. The thumbnails are generated as they should but the gallery is displaying only one image in each "category"... any idea why? 

http://karolinka.3d-sphere.com/

best regards,

Tomas

**Comment by Konstantin-Davidneko** [comment]
I have exactly same problem. Did anyone found solution?

**Comment by Konstantin-Davidneko** [comment]
Okey, I found solution!
nanoGallery files from "demonstration" folder should be linked to the page, instead of real ones. Do not know yet, where is problem, but that will help.

**Comment by Ruplahlava** [comment]
Hello,
im currently without computer (!!!) - for another 3 weeks.
I might look at it in work - if i have time, or after that 3 weeks :-/

**Comment by Konstantin-Davidneko** [comment]
Maybe you have idea, where problem can be? I am not so good in JS, but can try to look into...

**Comment by Ruplahlava** [comment]
This is almost sure php issue. Will try to look at it.

**Comment by Kris-B** [comment]
Please have a look at v0.9.0: https://github.com/Kris-B/nanoPhotosProvider/releases/tag/v0.9.0
Incompatibility with latest nanoGALLERY versions has been fixed, but please use nanoGALLERY v5.9.0beta1 which is located in the demonstration folder of nanoPhotosProvider (do not use v5.8.0).
