### ISSUE TITLE
Do not work correctly with last version (v5.7.0) of nanoGALLERY

### ISSUE THREAD

**Issue by Konstantin-Davidneko** [Kris-B/nanoPhotosProvider#4]
In demonstration used nanoGALLERY v5.3.0beta, and it works fine. However, if use nanoGALLERY v5.7.0, will be displayed only one picture from every instance. 

You can find more here: https://github.com/Kris-B/nanoPhotosProvider/issues/3

**Comment by Kris-B** [comment]
Please have a look at v0.9.0: https://github.com/Kris-B/nanoPhotosProvider/releases/tag/v0.9.0
Incompatibility with latest nanoGALLERY versions has been fixed, but please use nanoGALLERY v5.9.0beta1 which is located in the demonstration folder of nanoPhotosProvider (do not use v5.8.0).
