### ISSUE TITLE
New feature: album thumbnail that does not show up as image in the album

### ISSUE THREAD

**Issue by EelcoA** [Kris-B/nanoPhotosProvider#5]
This gives the option to set a specific thumbnail for the album for example a cropped part of one of the images without having to show it in the album.

My proposal:
- add an entry in the .cfg, for example: hidden_file="_hidden_".  
- use this to skip files in the whil loop that builds up the images

Then, when a file contains this string, it is not shown in the album. But when you name an image "@@@@@_hidden_.jpg" the result is that it is used as thumbnail, but not shown in the album.

**Comment by Kris-B** [comment]
possible with v0.9.2
