### ISSUE TITLE
Support empty directories

### ISSUE THREAD

**Issue by EelcoA** [Kris-B/nanoPhotosProvider#6]
nanoPhotosProvider can not handle empty directories because it tries (and fails) to set a thumbnail.

My proposal:
- when there are no images in a directory, create a transparent thumbnail "empty.png" and use this as thumbnail

Example result: 
![image](https://cloud.githubusercontent.com/assets/9035993/11036909/59d02dda-86fb-11e5-9771-131aaefb576d.png)

**Comment by Kris-B** [comment]
I don't see the benefit to support empty directories...

**Comment by EelcoA** [comment]
Well, software should be robust, now it isn't

Op do 24 dec. 2015 om 01:03 schreef Christophe Brisbois <
notifications@github.com>:

**Comment by Kris-B** [comment]
Well, you're right, software shouldn't break when it's improperly used. And users should read the documentations ;-)

This script is published on a collaborative platform. Some users ask for improvements and others push their own improvements. Both collaboration methods are welcomed here. Thanks.
