### ISSUE TITLE
Support directories with only sub directories

### ISSUE THREAD

**Issue by EelcoA** [Kris-B/nanoPhotosProvider#7]
Currently, a directory must contain at least one image because it needs it for creating a thumbnail.

My proposal:
- when no images in the directory, take the thumbnail of the 'first' sub directory. This should be done recursively, because that directory might only have sub directories as well, etc etc. And at the end, when the lowest directory is a empty directory, the thumbnail will become the "empty.png" See issue #6

**Comment by Kris-B** [comment]
Sounds too complicated...

**Comment by EelcoA** [comment]
HI Kris,

It's not, I have implemented it already in my own version. If interersted,
let me know

Op do 24 dec. 2015 om 01:04 schreef Christophe Brisbois <
notifications@github.com>:
